- src/Model/Areas.php
- src/Widget/Grid.php
- tests/Widget/GridTest.php
Introduces a "grid" widget which is a widget version of the Layout
> Grid Widget

- example/demo/src/Page/CanvasPage.php
- example/demo/src/Page/ImagePage.php
- example/demo/src/Page/SpritePage.php
- example/docs/getting-started/map.php
- example/docs/shape/circle.php
- example/docs/shape/imageShape.php
- example/docs/shape/line.php
- example/docs/shape/map.php
- example/docs/shape/points.php
- example/docs/shape/rectangle.php
- example/docs/shape/sprite.php
- example/docs/shape/textShape.php
- example/docs/widget/canvas.php
- src/Widget/Canvas.php
- tests/Adapter/Bdf/Shape/TextShapeTest.php
- tests/Widget/CanvasTest.php
Add a new static constructor to the canvas to improve DX
> Canvas static ctor

- CHANGELOG.md
- example/docs/shape/circle.php
- example/docs/shape/imageShape.php
- example/docs/shape/line.php
- example/docs/shape/map.php
- example/docs/shape/points.php
- example/docs/shape/rectangle.php
- example/docs/shape/sprite.php
- example/docs/shape/textShape.php
- example/docs/widget/canvas.php
- src/Widget/Canvas.php
- tests/Widget/CanvasTest.php
API method to avoid the use of the closure for simple requirements.
> API: Canvas draw(Widget)

- src/Adapter/Bdf/Shape/TextRenderer.php
Nothing functional was changed.
Edited: Failing test isn´t related.
> Chore: some cleanups on TextRenderer

- example/demo/src/App.php
- lib/term/README.md
- lib/term/src/Action/EnableMouseCapture.php
- lib/term/src/Actions.php
- lib/term/src/Event/MouseEvent.php
- lib/term/src/EventParser.php
- lib/term/src/MouseButton.php
- lib/term/src/MouseEventKind.php
- lib/term/src/Painter/AnsiPainter.php
- lib/term/src/ParseError.php
- lib/term/tests/EventParserTest.php
- lib/term/tests/Painter/AnsiPainterTest.php
Adds support for capturing mouse events
> Mouse Support

- example/demo/src/App.php
- example/docs/getting-started/map.php
- example/docs/shape/circle.php
- example/docs/shape/closureShape.php
- example/docs/shape/imageShape.php
- example/docs/shape/line.php
- example/docs/shape/map.php
- example/docs/shape/points.php
- example/docs/shape/rectangle.php
- example/docs/shape/sprite.php
- example/docs/shape/textShape.php
- example/docs/widget/block.php
- example/docs/widget/canvas.php
- example/docs/widget/chart.php
- example/docs/widget/grid.php
- example/docs/widget/itemList.php
- example/docs/widget/paragraph.php
- example/docs/widget/table.php
- src/DisplayBuilder.php
- src/Model/Display.php
- src/Widget/ClosureRenderer.php
- tests/Benchmark/Adapter/ImageMagick/ImageShapeBench.php
- tests/Benchmark/Model/DisplayBench.php
- tests/Benchmark/Widget/CanvasBench.php
- tests/DisplayBuilderTest.php
- tests/Example/DemoTest.php
- tests/Model/DisplayTest.php
Adds a DisplayBuilder as an entry point to the library.
> Display builder

- example/demo/src/App.php
- example/docs/getting-started/map.php
- example/docs/shape/circle.php
- example/docs/shape/closureShape.php
- example/docs/shape/imageShape.php
- example/docs/shape/line.php
- example/docs/shape/map.php
- example/docs/shape/points.php
- example/docs/shape/rectangle.php
- example/docs/shape/sprite.php
- example/docs/shape/textShape.php
- example/docs/widget/block.php
- example/docs/widget/canvas.php
- example/docs/widget/chart.php
- example/docs/widget/grid.php
- example/docs/widget/itemList.php
- example/docs/widget/paragraph.php
- example/docs/widget/table.php
- src/Model/Display.php
- tests/Benchmark/Adapter/ImageMagick/ImageShapeBench.php
- tests/Benchmark/Model/DisplayBench.php
- tests/Benchmark/Widget/CanvasBench.php
- tests/DisplayBuilderTest.php
- tests/Model/DisplayTest.php
Fixes #61 
Forces Display to ALWAYS be used with a Widget, you can no longer use a Closure to render.
> Remove drawWidget make draw(Widget)

- example/misc/inline.php
- src/Adapter/PhpTerm/PhpTermBackend.php
- src/DisplayBuilder.php
- src/Model/Backend.php
- src/Model/Backend/DummyBackend.php
- src/Model/Display.php
- src/Model/Viewport.php
- src/Model/Viewport/Fixed.php
- src/Model/Viewport/Fullscreen.php
- src/Model/Viewport/Inline.php
- tests/Model/DisplayTest.php
The inline viewport is interesting as it allows non-fullscreen usage, the following is from Ratatui:
> Viewports: inline and fixed

- docs/content/docs/reference/shapes/Map.md
- docs/content/docs/reference/widgets/Block.md
- docs/content/docs/reference/widgets/Chart.md
- docs/content/docs/reference/widgets/ImageWidget.md
- docs/content/docs/reference/widgets/ItemList.md
- docs/content/docs/reference/widgets/Paragraph.md
- docs/content/docs/reference/widgets/Table.md
- src/Extension/ImageMagick/ImageMagickExtension.php
- src/Extension/ImageMagick/ImageRegistry.php
- src/Extension/ImageMagick/Shape/ImagePainter.php
- src/Extension/ImageMagick/Widget/ImageRenderer.php
- src/Extension/ImageMagick/Widget/ImageWidget.php
- tests/Unit/Extension/ImageMagick/Widget/ImageRendererTest.php
As with ImageShape but will use a canvas matching the image dimensions
> Image widget

- .php-cs-fixer.dist.php
- example/demo/src/Page/CanvasScalingPage.php
- lib/term/src/EventProvider/LoadedEventProvider.php
- lib/term/src/Painter/HtmlCanvasPainter.php
- src/Bridge/PhpTerm/PhpTermBackend.php
- src/DisplayBuilder.php
- src/Extension/Core/Widget/ChartRenderer.php
- src/Extension/Core/Widget/ItemListRenderer.php
- src/Extension/ImageMagick/ImageRegistry.php
- src/Model/Widget/Text.php
- tests/Example/DemoTest.php
- tests/Unit/Model/BufferTest.php
I believe this is the last missing one, I promise. :blush:
> Chore: add `no_extra_blank_lines` rule to PHP-CS-FIXER

- example/demo/src/App.php
- src/Model/Style.php
- src/Model/Widget/Span.php
- tests/Unit/Model/SpanTest.php
Fixes: https://github.com/php-tui/php-tui/issues/121
> Fix: incorrect style patching in grapheme generation from `Span`

- src/Model/Style.php
> Chore: dries up `Style::path()`

- CHANGELOG.md
- lib/term/src/ClearType.php
- lib/term/src/Painter/AnsiPainter.php
- lib/term/tests/Painter/AnsiPainterTest.php
- src/Bridge/PhpTerm/PhpTermBackend.php
- src/Model/Backend.php
- src/Model/Backend/DummyBackend.php
- src/Model/Buffer.php
- src/Model/ClearType.php
- src/Model/Display.php
- src/Model/Position.php
- src/Model/Viewport.php
- src/Model/Viewport/Fixed.php
- src/Model/Viewport/Fullscreen.php
- src/Model/Viewport/Inline.php
- tests/Unit/Bridge/PhpTerm/PhpTermBackendTest.php
- tests/Unit/Model/DisplayTest.php
- tests/Unit/Model/PositionTest.php
- tests/Unit/Model/Viewport/FixedTest.php
Fixes #120 
Allows for better inline interfaces (can drop text before the view port, f.e. log lines)
> Gh 120 Support for Display#insertBefore viewport

- example/demo/src/App.php
- example/demo/src/Page/BarChartPage.php
- example/demo/src/Page/BlocksPage.php
- example/demo/src/Page/CanvasPage.php
- example/demo/src/Page/ChartPage.php
- example/demo/src/Page/GaugePage.php
- example/demo/src/Page/SpritePage.php
- example/demo/src/Page/TablePage.php
- src/Extension/Core/Widget/BarChartRenderer.php
- src/Extension/Core/Widget/BlockRenderer.php
- src/Extension/Core/Widget/ListRenderer.php
- src/Model/Style.php
- src/Model/Text/Span.php
- src/Model/Text/SpanParser.php
- tests/Unit/Model/StyleTest.php
Closes: https://github.com/php-tui/php-tui/issues/151
> Implements `Styleable` on `Style`

- CHANGELOG.md
- example/demo/src/Page/ChartPage.php
- example/docs/widget/chartWidget.php
- src/Extension/Core/Widget/Chart/Axis.php
- src/Extension/Core/Widget/ChartRenderer.php
- src/Model/Math/VectorUtil.php
- tests/Unit/Extension/Core/Widget/ChartWidgetTest.php
- tests/Unit/Model/Math/VectorUtilTest.php
> Chart Improvements

- CHANGELOG.md
- example/demo/src/Page/BarChartPage.php
- src/Extension/Core/Widget/BarChartRenderer.php
- tests/Unit/Extension/Core/Widget/BarChartRendererTest.php
> Gh 160: horiztonal bar chart fix

- example/demo/demo.tape
This is a preference thing, so you can feel free to close. :smile: 
I find the border beautiful because it matches the PHP-TUI logo colors :heart_eyes:
> Chore: add border to generated vhs gif

- CHANGELOG.md
- src/Model/Layout/Layout.php
- src/Model/Margin.php
- tests/Unit/Model/AreaTest.php
Following: https://github.com/php-tui/php-tui/pull/165
> Add new builder methods to `Margin`

- src/Extension/Core/Widget/Block/Padding.php
- tests/Unit/Extension/Core/Widget/Block/PaddingTest.php
Closes: https://github.com/php-tui/php-tui/issues/174
> Make `Padding` immutable

- CHANGELOG.md
- src/Extension/Core/Widget/ChartRenderer.php
- src/Model/Display/Buffer.php
This fixes behaviors on Gauge Widget and probably others.
> Fix `putBuffer()`  behaviour

- example/demo/src/App.php
Just to help make obvious that is possible to use this way. :nail_care:
> Chore: use `Line::parse()`

- CHANGELOG.md
- example/demo/src/App.php
- example/demo/src/Page/ItemListPage.php
- src/Extension/Core/Widget/ParagraphWidget.php
- src/Model/Text/Line.php
Closes: https://github.com/php-tui/php-tui/issues/188
> Make `Line::fromSpans()` variadic

- CHANGELOG.md
- src/Extension/Core/Widget/BlockRenderer.php
- tests/Example/snapshot/Blocks.snapshot
- tests/Unit/Extension/Core/Widget/BlockRendererTest.php
> Fix adjacent borders

- src/Display/Buffer.php
Reduces one function call in the loop.
Bench:
```
<current>
+-----------------+---------------------------+---------+----------+----------+----------+--------+-----------+
| benchmark       | subject                   | memory  | min      | max      | mode     | rstdev | stdev     |
+-----------------+---------------------------+---------+----------+----------+----------+--------+-----------+
| DisplayBench    | benchRenderFrame ()       | 8.339mb | 22.947ms | 23.468ms | 23.110ms | ±0.72% | 166.902μs |
| ImageShapeBench | benchImageShape ()        | 8.191mb | 13.166ms | 13.252ms | 13.179ms | ±0.25% | 32.921μs  |
| CanvasBench     | benchLowResolutionMap ()  | 8.327mb | 14.895ms | 15.140ms | 15.062ms | ±0.45% | 67.305μs  |
| CanvasBench     | benchHighResolutionMap () | 8.362mb | 19.089ms …
```
> Chore: minor change in Buffer diff

- CHANGELOG.md
- src/Display/Buffer.php
- tests/Example/snapshot/List.snapshot
- tests/Unit/Model/Display/BufferTest.php
> Gh 211: line truncation

- example/demo/src/ActivePage.php
- example/demo/src/App.php
- example/demo/src/Page/WindowPage.php
- src/Display/Area.php
- src/Extension/Core/Widget/Buffer/BufferContext.php
This is a simple POC for making a draggable Window just to see if it's possible and if it's worth creating a "window" widget.
-
> POC for window
